### ISSUE TITLE
Incorrect results and "Requested value is not set"

### ISSUE THREAD

**Issue by ParticleMon** [grtetrault/pcre2.py#3]
Among several expressions that succeed (all vetted with regex101.com and the re package), some I see fail on pcre2 0.3.0 in one of two ways:
1. Incorrect result
- ``var = pcre2.compile(r'\s+$', options = pcre2.G | pcre2.M, jit = True).substitute('', _var)``
var = re.compile(r'\s+$', flags = re.M).sub('', _var)

- ``var = pcre2.compile(r'\s*\n\s+', options = pcre2.G | pcre2.M, jit = True).substitute(' ', _var)``
var = re.compile(r'\s*\n\s+', flags = re.M).sub(' ', _var)

2. pcre2.exceptions.LibraryError: Requested value is not set
- ``var = pcre2.compile(r'^\s*(\w\d\.\w+\s+\w\d+)*,*$|^\s+.*|\s+$|SELECT', options = pcre2.G | pcre2.I | pcre2.M, jit = True).substitute('$1', _var)``
var = re.compile(r'^\s*(\w\d\.\w+\s+\w\d+)*,*$|^\s+.*|\s+$|SELECT', flags = re.I | re.M).sub(r'\1', _var)

- ``var = pcre2.compile(r'(^\s*SELECT[\s\S]+?)(?=^\s*\),*$)|(^\s*WITH[^(]+\(|^\s*\),[^(]+\(|^\s*\)[^(]+(?=SELECT)|^\s*\)$)', options = pcre2.G | pcre2.I | pcre2.M, jit = True).findall(_var)``
var = re.compile(r'(^\s*SELECT[\s\S]+?)(?=^\s*\),*$)|(^\s*WITH[^(]+\(|^\s*\),[^(]+\(|^\s*\)[^(]+(?=SELECT)|^\s*\)$)', flags = re.I | re.M).findall(_var)

Python 3.10.12
PyCharm 2023.2.1

**Comment by grtetrault** [comment]
Hi @ParticleMon what does `_var` refer to in these?

**Comment by ParticleMon** [comment]
In these, `_var` (and `var`) is a variable either passed to the containing method or that modifies a previous variable assignment, perhaps itself.

**Comment by rootsmusic** [comment]
@ParticleMon  Note that the Python emulation in regex101.com uses [pcre](https://www.pcre.org/original/doc/html/), which is at end of life.

**Comment by ParticleMon** [comment]
> Note that the Python emulation in regex101.com uses [pcre](https://www.pcre.org/original/doc/html/), which is at end of life.

My results are from PCRE2 on regex101.com (which I see that I did not explicitly state).

**Comment by anton-dubrovin** [comment]
Any updates about the issue?

**Comment by grtetrault** [comment]
I've had some time to look through this issue and found the following:

1. For the incorrect results - the option `pcre2.G` is defined as `SubstituteOption.GLOBAL` and must be set on the *substitute* call, not during compilation. E.g., if you do the following I think you'll end up with the results you expect:
```
s = "foo    \nbar    \n"
patn = pcre2.compile(r"\s+$", options=pcre2.M, jit=True)
result = patn.substitute("", s, options=pcre2.G)
assert result == "foo\nbar"
```

2. For the exceptions, these are because PCRE2 does not by default replace unmatched group with empty strings. There is the option `SubstituteOption.UNSET_EMPTY` to set this behavior when substituting, but I'm planning on always setting this to keep in line with Python's `re`. This is the same reason why the `findall` call gives an error, however there is no way at the moment to set a default value for unmatched groups - I'm also planning on making a change to allow this.

**Comment by grtetrault** [comment]
Closing this issue with #7 - this implements the changes I described above. Feel free to open another issue if this doesn't capture everything you mentioned.
